/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: News App
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ipca.example.topnews.repository.backend.apis

import ipca.example.topnews.repository.backend.models.Articles
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface NewsApi {
    /**
     * Get user playlists
     * The endpoint is owned by defaultname service owner
     * @param country (optional)
     * @param category (optional)
     * @param apiKey (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("top-headlines")
    suspend fun topHeadlinesGet(
        @retrofit2.http.Query("country") country: String?,
        @retrofit2.http.Query("category") category: String?,
        @retrofit2.http.Query("apiKey") apiKey: String?
    ): Articles
}
