/**
* News App
* newsapi api with one end-point.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.Article

/**
 * 
 * @param status 
 * @param totalResults 
 * @param articles 
 */
data class Articles (
    var status: kotlin.String? = null,
    var totalResults: kotlin.Int? = null,
    var articles: kotlin.Array<Article>? = null,
) {

}

