---
openapi: 3.0.1
info:
  version: '1.0.0'
  title: News App
  description: newsapi api with one end-point.
  
servers:
  - url: https://newsapi.org/v2
    description: News API is a simple HTTP REST API for searching and retrieving live articles from all over the web
  
paths:
  /top-headlines:
    get:
      security:
        - ApiKeyAuth: []
      description: Get user playlists
      tags:
        - News
      parameters:
        - in: query
          name: country
          required: false
          schema:
            type: string
        - in: query
          name: category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Articles"
            

components:
  schemas:
    Source:
      type: object
      properties: 
        id:
          type: string
        name:
          type: string
          
    Article:
      type: object
      properties:
        user: 
          "$ref": "#/components/schemas/Source"
        author:
          type: string
        title:
          type: string
        description:
          type: string
        url:
          type: string
        urlToImage:
          type: string
        publishedAt:
          type: string
        content:
          type: string
    
    Articles:
      type: object
      properties:
        status:
          type: string
        totalResults:
          type: integer
        articles:
          type: array
          items: 
            "$ref": "#/components/schemas/Article"

  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: query       # can be "header", "query" or "cookie"
      name: apiKey

security:
  - ApiKeyAuth: [] 