/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: News App
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ipca.example.topnews.repository.backend.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property status
 * @property totalResults
 * @property articles
 */
@JsonClass(generateAdapter = true)
data class Articles(
    @Json(name = "status") @field:Json(name = "status") var status: String? = null,
    @Json(name = "totalResults") @field:Json(name = "totalResults") var totalResults: Int? = null,
    @Json(name = "articles") @field:Json(name = "articles") var articles: List<Article>? = null
)
