/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: News App
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ipca.example.topnews.repository.backend.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property source
 * @property author
 * @property title
 * @property description
 * @property url
 * @property urlToImage
 * @property publishedAt
 * @property content
 */
@JsonClass(generateAdapter = true)
data class Article(
    @Json(name = "source") @field:Json(name = "source") var source: Source? = null,
    @Json(name = "author") @field:Json(name = "author") var author: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "url") @field:Json(name = "url") var url: String? = null,
    @Json(name = "urlToImage") @field:Json(name = "urlToImage") var urlToImage: String? = null,
    @Json(name = "publishedAt") @field:Json(name = "publishedAt") var publishedAt: String? = null,
    @Json(name = "content") @field:Json(name = "content") var content: String? = null
)
