/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: News App
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ipca.example.topnews.repository.backend.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property name
 */
@JsonClass(generateAdapter = true)
data class Source(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
