//
// Article.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Article: Codable {

    public var user: Source?
    public var author: String?
    public var title: String?
    public var _description: String?
    public var url: String?
    public var urlToImage: String?
    public var publishedAt: String?
    public var content: String?

    public init(user: Source? = nil, author: String? = nil, title: String? = nil, _description: String? = nil, url: String? = nil, urlToImage: String? = nil, publishedAt: String? = nil, content: String? = nil) {
        self.user = user
        self.author = author
        self.title = title
        self._description = _description
        self.url = url
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content
    }

    public enum CodingKeys: String, CodingKey { 
        case user
        case author
        case title
        case _description = "description"
        case url
        case urlToImage
        case publishedAt
        case content
    }

}
