//
// Articles.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Articles: Codable {

    public var status: String?
    public var totalResults: Int?
    public var articles: [Article]?

    public init(status: String? = nil, totalResults: Int? = nil, articles: [Article]? = nil) {
        self.status = status
        self.totalResults = totalResults
        self.articles = articles
    }


}
