//
// NewsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class NewsAPI {
    /**

     - parameter country: (query)  (optional)
     - parameter category: (query)  (optional)
     - parameter apiKey: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func topHeadlinesGet(country: String? = nil, category: String? = nil, apiKey: String? = nil, completion: @escaping ((_ data: Articles?,_ error: Error?) -> Void)) {
        topHeadlinesGetWithRequestBuilder(country: country, category: category, apiKey: apiKey).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /top-headlines
     - Get user playlists
     - examples: [{contentType=application/json, example={
  "totalResults" : 0,
  "articles" : [ {
    "publishedAt" : "publishedAt",
    "author" : "author",
    "urlToImage" : "urlToImage",
    "description" : "description",
    "source" : {
      "name" : "name",
      "id" : "id"
    },
    "title" : "title",
    "url" : "url",
    "content" : "content"
  }, {
    "publishedAt" : "publishedAt",
    "author" : "author",
    "urlToImage" : "urlToImage",
    "description" : "description",
    "source" : {
      "name" : "name",
      "id" : "id"
    },
    "title" : "title",
    "url" : "url",
    "content" : "content"
  } ],
  "status" : "status"
}}]
     
     - parameter country: (query)  (optional)
     - parameter category: (query)  (optional)
     - parameter apiKey: (query)  (optional)

     - returns: RequestBuilder<Articles> 
     */
    open class func topHeadlinesGetWithRequestBuilder(country: String? = nil, category: String? = nil, apiKey: String? = nil) -> RequestBuilder<Articles> {
        let path = "/top-headlines"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "country": country, 
            "category": category, 
            "apiKey": apiKey
        ])

        let requestBuilder: RequestBuilder<Articles>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
